import { useState } from "react";
import SoapTypeList from "@/components/SoapTypeList";
import Head from "next/head";

export default function Home() {
  const [query, setQuery] = useState("");
  return (
    <>
      <Head>
        <title>Soap by Seá
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

       
      </Head>
      <main className="mx-auto container m-6">
        <div className="mb-6">
          <span className="span"></span>
        </div>
        <SoapTypeList query={query} />
      </main>
    </>
  );
}